# Generated by Django 3.0.2 on 2020-02-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
        ('Course', '0006_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Questions',
            field=models.ManyToManyField(blank=True, null=True, to='Question.Question'),
        ),
    ]
