# Generated by Django 2.2.5 on 2020-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
        ('Course', '0006_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Questions',
            field=models.ManyToManyField(blank=True, null=True, to='Question.Question'),
        ),
        migrations.AddField(
            model_name='course',
            name='Status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'archived')], default='1', max_length=20),
        ),
    ]
