# Generated by Django 3.0.2 on 2020-02-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20200202_2347'),
        ('Course', '0007_course_questions'),
    ]

    operations = [
    ]
