# Generated by Django 3.0.2 on 2020-02-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Question.Question')),
                ('dummy', models.TextField(blank=True, null=True)),
            ],
            bases=('Question.question',),
        ),
    ]
